# Generated by Django 5.0.6 on 2024-07-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
